package com.example.Loja_jogos_digitais.model;

public enum Categoria {
    ACAO, AVENTURA, RPG, MMORPG, ESTRATEGIA, FPS, SIMULACAO, ESPORTES, MOBA, PLATAFORMA, LUTA, BATTLE_ROYALE, EDUCACIONAL, ROGUELIKE, ROGUELITE, TABULEIRO, CARTAS, POPULARES, HISTORIA, MUNDO_ABERTO
}
